import { createPage } from '../atoms/page';
import { getCloudRunUrl } from '../index';

/**
 * Page: Smart Email Manager Settings
 * Allows users to tune the AI logic and trigger manual syncs.
 */
export function createSettingsPage() {
  const props = PropertiesService.getScriptProperties();
  const cloudRunUrl = getCloudRunUrl();
  const userEmail = Session.getActiveUser().getEmail();

  // Default fallback settings
  let currentSettings = {
    "MAX_SEMANTIC_LABELS": 5,
    "REORG_COOLDOWN_HOURS": 1,
    "BACKLOG_THRESHOLD": 15,
    "DEFAULT_SIMILARITY_THRESHOLD": 0.85,
    "ADAPTIVE_THRESHOLD_HYSTERESIS": 0.85,
    "BATCH_CLASSIFICATION_FREQUENCY": 10,
    "AUTO_SYNC_NEW_EMAILS": true
  };

  // 1. Fetch current settings from backend
  try {
    const response = UrlFetchApp.fetch(`${cloudRunUrl}/api/settings?user_email=${encodeURIComponent(userEmail)}`, {
      method: "get",
      muteHttpExceptions: true
    });
    if (response.getResponseCode() === 200) {
      currentSettings = JSON.parse(response.getContentText());
    }
  } catch (e) {
    console.error("Failed to fetch settings from backend: " + e.toString());
  }

  const sections = [];

  // --- AUTOMATED WORKFLOWS ---
  const autoSection = CardService.newCardSection()
    .setHeader("Automated Workflows")
    .addWidget(CardService.newTextParagraph().setText("New mail can be sent directly on arrival. This keeps your email manager and analytics up to date."))
    .addWidget(CardService.newSelectionInput()
      .setType(CardService.SelectionInputType.CHECK_BOX)
      .setFieldName("auto_sync")
      .addItem("Auto-sync new emails after arrival", "true", currentSettings.AUTO_SYNC_NEW_EMAILS));
  sections.push(autoSection);

  // --- MANUAL WORKFLOWS ---
  const lastVerified = props.getProperty("LAST_VERIFIED") || "Never";
  const lastSync = props.getProperty("LAST_SYNC_TIMESTAMP") || "Never";

  const manualSection = CardService.newCardSection()
    .setHeader("Manual Workflows")
    .addWidget(CardService.newTextButton()
      .setText("Check Connection")
      .setOnClickAction(CardService.newAction().setFunctionName("onCheckConnections")))
    .addWidget(CardService.newTextParagraph().setText(`<font color="#666666">Last Verified: ${lastVerified}</font>`))
    .addWidget(CardService.newSelectionInput()
      .setType(CardService.SelectionInputType.DROPDOWN)
      .setTitle("Lookback Range")
      .setFieldName("sync_range")
      .addItem("Last 30 days", "30", true)
      .addItem("Last 60 days", "60", false)
      .addItem("Last 3 months", "90", false)
      .addItem("Last 6 months", "180", false)
      .addItem("Last year", "365", false))
    .addWidget(CardService.newTextButton()
      .setText("Sync to MongoDB")
      .setOnClickAction(CardService.newAction().setFunctionName("onManualSync")))
    .addWidget(CardService.newTextParagraph().setText(`<font color="#666666">Last Timestamp Sync: ${lastSync}</font>`));
  sections.push(manualSection);

  // --- SEM CONFIGURATIONS ---
  const configSection = CardService.newCardSection()
    .setHeader("Smart Email Manager Configurations");

  // Max Labels
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Max Number of labels generated</b><br/><small>Set the max number of gmail labels to be generated by the email manager. The labels are similar to bucket to which emails are organized into.</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("max_labels")
    .setTitle("Current: " + currentSettings.MAX_SEMANTIC_LABELS)
    .setValue(currentSettings.MAX_SEMANTIC_LABELS.toString()));

  // Similarity Threshold
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Stability & Classification (Path 3)</b><br/><small>Controls how 'picky' the agent is. Lowering it makes categorization easier; raising it increases accuracy.</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("sim_threshold")
    .setTitle("Similarity Threshold (e.g. 0.85)")
    .setValue(currentSettings.DEFAULT_SIMILARITY_THRESHOLD.toString()));

  // Reorg Cooldown
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Reorganization & Discovery (Path 2)</b><br/><small>The 'speed limit' for label changes. Lowering it (e.g., 0.25) makes the agent react faster to new types of emails.</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("reorg_cooldown")
    .setTitle("Cooldown Hours (e.g. 1)")
    .setValue(currentSettings.REORG_COOLDOWN_HOURS.toString()));

  // Backlog Threshold
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Backlog Threshold</b><br/><small>Min number of emails in unclassified before creating a new label.</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("backlog_threshold")
    .setTitle("Backlog size (e.g. 15)")
    .setValue(currentSettings.BACKLOG_THRESHOLD.toString()));

  // Adaptive Learning
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Adaptive Learning</b><br/><small>Sets the bar for label integrity relative to the starting score. (0.70 - 0.90)</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("hysteresis")
    .setTitle("Hysteresis (e.g. 0.85)")
    .setValue(currentSettings.ADAPTIVE_THRESHOLD_HYSTERESIS.toString()));

  // Batch Frequency
  configSection.addWidget(CardService.newTextParagraph().setText("<b>Performance & Rate Limiting</b><br/><small>How often the agent pauses to run the classifier during a large sync.</small>"));
  configSection.addWidget(CardService.newTextInput()
    .setFieldName("batch_freq")
    .setTitle("Batch Frequency (e.g. 10)")
    .setValue(currentSettings.BATCH_CLASSIFICATION_FREQUENCY.toString()));

  configSection.addWidget(CardService.newTextButton()
    .setText("Save Configurations")
    .setOnClickAction(CardService.newAction().setFunctionName("onSaveSettings"))
    .setTextButtonStyle(CardService.TextButtonStyle.FILLED));

  sections.push(configSection);

  return createPage(
    "SettingsPage",
    "Rapid Agent Gmail Suite",
    "Smart Email Manager",
    "This feature will organize all your mails into appropiate label groups so you can know where your most important mails are when you access.",
    sections
  );
}
