/**
 * Component for Smart Email Manager UI.
 */

/**
 * Creates the Smart Email Manager Card.
 * @param connectionStatus Current status of the connection ("Success" or "Failure" or "Not verified").
 * @param connectionTimestamp Timestamp of the last connection verification.
 * @param syncPercentage Current sync percentage.
 * @param syncTimestamp Timestamp of the last sync.
 */
function createSmartEmailManagerCard(
  connectionStatus: string = "Success",
  connectionTimestamp: string = new Date().toLocaleString(),
  syncPercentage: string = "100",
  syncTimestamp: string = new Date().toLocaleString()
) {
  const cardBuilder = CardService.newCardBuilder().setName("SMART_EMAIL_MANAGER");

  // Header Section
  const headerSection = CardService.newCardSection()
    .addWidget(
      CardService.newTextParagraph().setText(
        '<b><font color="#1A1A1A">Rapid Agent Gmail Suite</font></b><br/>' +
        '<i><font color="#333333">Smart Email Manager</font></i>'
      )
    )
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">This feature will organize all your mails into appropiate label groups so you can know where your most important mails are when you access.</font>'
      )
    );
  cardBuilder.addSection(headerSection);

  // Automated Workflows Section
  const autoWorkflowsSection = CardService.newCardSection()
    .setHeader("Automated Workflows")
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">New mail can be sent directly on arrival. This keeps your email manager and analytics upto date</font>'
      )
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("auto_sync_emails")
        .addItem("Auto-sync new emails after arrival", "true", true)
    );
  cardBuilder.addSection(autoWorkflowsSection);

  // Manual Workflows Section
  const connectionStatusColor = connectionStatus === "Success" ? "#0F9D58" : (connectionStatus === "Not verified" ? "#999999" : "#DB4437");
  const connectionTimestampDisplay = connectionTimestamp !== "N/A" ? `<br/><font color="#999999">${connectionTimestamp}</font>` : "";
  
  const syncStatusDisplay = syncPercentage === "0" ? '<font color="#999999">Yet to sync</font>' : `(${syncPercentage}%) ....`;
  const syncTimestampDisplay = syncTimestamp !== "N/A" ? `<br/><font color="#999999">${syncTimestamp}</font>` : "";

  const manualWorkflowsSection = CardService.newCardSection()
    .setHeader("Manual Workflows")
    .addWidget(
      CardService.newButtonSet()
        .addButton(
          CardService.newTextButton()
            .setText("Check connection")
            .setTextButtonStyle(CardService.TextButtonStyle.OUTLINED)
            .setOnClickAction(CardService.newAction().setFunctionName("onCheckConnectionSEM"))
        )
    )
    .addWidget(
      CardService.newTextParagraph().setText(
        `<b>Last Verified:</b> <font color="${connectionStatusColor}">${connectionStatus}</font>${connectionTimestampDisplay}`
      )
    )
    .addWidget(
      CardService.newButtonSet()
        .addButton(
          CardService.newTextButton()
            .setText("Sync to mongoDB")
            .setTextButtonStyle(CardService.TextButtonStyle.OUTLINED)
            .setOnClickAction(CardService.newAction().setFunctionName("onSyncMongoDBSEM"))
        )
    )
    .addWidget(
      CardService.newTextParagraph().setText(
        `<b>Last Timestamp sync:</b> ${syncStatusDisplay}${syncTimestampDisplay}`
      )
    );
  cardBuilder.addSection(manualWorkflowsSection);

  // Smart Email Manager Configurations
  const configSection = CardService.newCardSection()
    .setHeader("Smart Email Manager Configurations")
    // Group 1
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">Set the max number of gmail labels to be generated by the email manager. The labels are similar to bucket to which emails are organized into.</font>'
      )
    )
    .addWidget(
      CardService.newTextInput()
        .setFieldName("max_labels")
        .setTitle("Max Number of labels generated")
        .setValue("5")
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("suggest_reconsider_labels")
        .addItem("Suggest me to reconsider number of labels to optimal number. (via mail)", "true", false)
    )
    // Group 2
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">Set the max semantic score that the manager can agree upon. Below this threshold the manager will reorganize mails to meet the balanced semantic scores, if necessary generate new appropiate labels.</font>'
      )
    )
    .addWidget(
      CardService.newTextInput()
        .setFieldName("min_semantic_score")
        .setTitle("Min Semantic scores")
        .setValue("60%")
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("notify_before_change")
        .addItem("Notify me before performing a change to old labels.", "true", false)
    );
  cardBuilder.addSection(configSection);

  // Footer Section
  const footerSection = CardService.newCardSection()
    .addWidget(CardService.newDivider())
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel("Terms & Conditions | Privacy Policy | Support")
        .setWrapText(true)
    )
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel(
          'Website: <a href="https://www.rahulgputcha.com">www.rahulgputcha.com</a><br/>Developer Email: rahulgputcha@gmail.com'
        )
        .setWrapText(true)
    )
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel(
          "© Copyright 2026 Rahul Gautham Putcha, Sree Harshitha Jonnalagadda.<br/>All rights reserved"
        )
        .setWrapText(true)
    );
  cardBuilder.addSection(footerSection);

  return cardBuilder.build();
}

/**
 * Action handler for checking the connection.
 */
function onCheckConnectionSEM(e: any) {
  const now = new Date().toLocaleString();
  return CardService.newActionResponseBuilder()
    .setNavigation(
      CardService.newNavigation().updateCard(
        createSmartEmailManagerCard("Success", now, "100", now)
      )
    )
    .setNotification(CardService.newNotification().setText("Connection verified successfully."))
    .build();
}

/**
 * Action handler for syncing to MongoDB.
 */
function onSyncMongoDBSEM(e: any) {
  const now = new Date().toLocaleString();
  return CardService.newActionResponseBuilder()
    .setNavigation(
      CardService.newNavigation().updateCard(
        createSmartEmailManagerCard("Success", now, "100", now)
      )
    )
    .setNotification(CardService.newNotification().setText("Synced to MongoDB successfully."))
    .build();
}

/**
 * Navigation function to show the Smart Email Manager card.
 */
function showSmartEmailManager(e: any) {
  return CardService.newActionResponseBuilder()
    .setNavigation(
      CardService.newNavigation().pushCard(createSmartEmailManagerCard("Not verified", "N/A", "0", "N/A"))
    )
    .build();
}
