/**
 * Component for Smart Email Manager UI.
 */

/**
 * Creates the Smart Email Manager Card.
 * @param connectionStatus Current status of the connection ("Success" or "Failure" or "Not verified").
 * @param connectionTimestamp Timestamp of the last connection verification.
 * @param syncPercentage Current sync percentage.
 * @param syncTimestamp Timestamp of the last sync.
 * @param message Optional message to display (e.g., verification result).
 */
function createSmartEmailManagerCard(
  connectionStatus: string = "Not verified",
  connectionTimestamp: string = "N/A",
  syncPercentage: string = "0",
  syncTimestamp: string = "N/A",
  message: string = "",
) {
  const cardBuilder = CardService.newCardBuilder().setName(
    "SMART_EMAIL_MANAGER",
  );

  // Header Section
  const headerSection = CardService.newCardSection()
    .addWidget(
      CardService.newTextParagraph().setText(
        '<b><font color="#1A1A1A">Rapid Agent Gmail Suite</font></b><br/>' +
          '<i><font color="#333333">Smart Email Manager</font></i>',
      ),
    )
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">This feature will organize all your mails into appropriate label groups so you can know where your most important mails are when you access.</font>',
      ),
    );

  if (message) {
    headerSection.addWidget(
      CardService.newTextParagraph().setText(
        `<font color="#0F9D58">${message}</font>`,
      ),
    );
  }

  cardBuilder.addSection(headerSection);

  // Automated Workflows Section
  const autoWorkflowsSection = CardService.newCardSection()
    .setHeader("Automated Workflows")
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">New mail can be sent directly on arrival. This keeps your email manager and analytics upto date</font>',
      ),
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("auto_sync_emails")
        .addItem("Auto-sync new emails after arrival", "true", true),
    );
  cardBuilder.addSection(autoWorkflowsSection);

  // Manual Workflows Section
  const connectionStatusColor =
    connectionStatus === "Success"
      ? "#0F9D58"
      : connectionStatus === "Not verified"
        ? "#999999"
        : "#DB4437";
  const connectionTimestampDisplay =
    connectionTimestamp !== "N/A"
      ? `<br/><font color="#999999">${connectionTimestamp}</font>`
      : "";

  const syncStatusDisplay =
    syncPercentage === "0"
      ? '<font color="#999999">Yet to sync</font>'
      : `(${syncPercentage}%) ....`;
  const syncTimestampDisplay =
    syncTimestamp !== "N/A"
      ? `<br/><font color="#999999">${syncTimestamp}</font>`
      : "";

  const manualWorkflowsSection = CardService.newCardSection()
    .setHeader("Manual Workflows")
    .addWidget(
      CardService.newButtonSet()
        .addButton(
          CardService.newTextButton()
            .setText("Check connection")
            .setTextButtonStyle(CardService.TextButtonStyle.OUTLINED)
            .setOnClickAction(
              CardService.newAction().setFunctionName("onCheckConnectionSEM"),
            ),
        )
        .addButton(
          CardService.newTextButton()
            .setText("Update backend")
            .setTextButtonStyle(CardService.TextButtonStyle.OUTLINED)
            .setOnClickAction(
              CardService.newAction().setFunctionName("onUpdateBackendSEM"),
            ),
        ),
    );

  manualWorkflowsSection
    .addWidget(
      CardService.newTextParagraph().setText(
        `<b>Last Verified:</b> <font color="${connectionStatusColor}">${connectionStatus}</font>${connectionTimestampDisplay}`,
      ),
    )
    .addWidget(
      CardService.newButtonSet().addButton(
        CardService.newTextButton()
          .setText("Sync to mongoDB")
          .setTextButtonStyle(CardService.TextButtonStyle.OUTLINED)
          .setOnClickAction(
            CardService.newAction().setFunctionName("onSyncMongoDBSEM"),
          ),
      ),
    )
    .addWidget(
      CardService.newTextParagraph().setText(
        `<b>Last Timestamp sync:</b> ${syncStatusDisplay}${syncTimestampDisplay}`,
      ),
    );
  cardBuilder.addSection(manualWorkflowsSection);

  // Smart Email Manager Configurations
  const configSection = CardService.newCardSection()
    .setHeader("Smart Email Manager Configurations")
    // Group 1
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">Set the max number of gmail labels to be generated by the email manager. The labels are similar to bucket to which emails are organized into.</font>',
      ),
    )
    .addWidget(
      CardService.newTextInput()
        .setFieldName("max_labels")
        .setTitle("Max Number of labels generated")
        .setValue("5"),
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("suggest_reconsider_labels")
        .addItem(
          "Suggest me to reconsider number of labels to optimal number. (via mail)",
          "true",
          false,
        ),
    )
    // Group 2
    .addWidget(
      CardService.newTextParagraph().setText(
        '<font color="#999999">Set the max semantic score that the manager can agree upon. Below this threshold the manager will reorganize mails to meet the balanced semantic scores, if necessary generate new appropriate labels.</font>',
      ),
    )
    .addWidget(
      CardService.newTextInput()
        .setFieldName("min_semantic_score")
        .setTitle("Min Semantic scores")
        .setValue("60%"),
    )
    .addWidget(
      CardService.newSelectionInput()
        .setType(CardService.SelectionInputType.CHECK_BOX)
        .setFieldName("notify_before_change")
        .addItem(
          "Notify me before performing a change to old labels.",
          "true",
          false,
        ),
    );
  cardBuilder.addSection(configSection);

  // Footer Section
  const footerSection = CardService.newCardSection()
    .addWidget(CardService.newDivider())
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel("Terms & Conditions | Privacy Policy | Support")
        .setWrapText(true),
    )
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel(
          'Website: <a href="https://www.rahulgputcha.com">www.rahulgputcha.com</a><br/>Developer Email: rahulgputcha@gmail.com',
        )
        .setWrapText(true),
    )
    .addWidget(
      CardService.newDecoratedText()
        .setBottomLabel(
          "© Copyright 2026 Rahul Gautham Putcha, Sree Harshitha Jonnalagadda.<br/>All rights reserved",
        )
        .setWrapText(true),
    );
  cardBuilder.addSection(footerSection);

  return cardBuilder.build();
}

/**
 * Action handler for checking the connection.
 */
function onCheckConnectionSEM(e: any) {
  const now = new Date().toLocaleString();
  return CardService.newActionResponseBuilder()
    .setNavigation(
      CardService.newNavigation().updateCard(
        createSmartEmailManagerCard("Success", now, "100", now),
      ),
    )
    .setNotification(
      CardService.newNotification().setText(
        "Connection verified successfully.",
      ),
    )
    .build();
}

/**
 * Action handler for updating the backend.
 * Triggers an automated Cloud Build.
 */
function onUpdateBackendSEM(e: any) {
  return onTriggerCloudBuildSEM(e);
}

/**
 * Automatically triggers a GCP Cloud Build for the agent.
 */
function onTriggerCloudBuildSEM(e: any) {
  const accessToken = ScriptApp.getOAuthToken();
  const projectId = "983993789043"; // Your GCP Project ID
  const repoUrl = "https://github.com/RPG-coder/rapid-agent-gmail-suites";
  
  // Cloud Build Trigger API
  const url = `https://cloudbuild.googleapis.com/v1/projects/${projectId}/builds`;
  
  const buildRequest = {
    "source": {
      "gitSource": {
        "url": repoUrl,
        "dir": "agents/smart-email-manager",
        "revision": "main"
      }
    },
    "steps": [
      {
        "name": "gcr.io/cloud-builders/docker",
        "args": ["build", "-t", `gcr.io/${projectId}/smart-email-manager-agent`, "."]
      },
      {
        "name": "gcr.io/cloud-builders/docker",
        "args": ["push", `gcr.io/${projectId}/smart-email-manager-agent`]
      },
      {
        "name": "gcr.io/google.com/cloudsdktool/cloud-sdk",
        "entrypoint": "gcloud",
        "args": [
          "run", "deploy", "smart-email-manager-agent",
          "--image", `gcr.io/${projectId}/smart-email-manager-agent`,
          "--region", "us-central1",
          "--platform", "managed",
          "--allow-unauthenticated"
        ]
      }
    ]
  };

  try {
    const response = UrlFetchApp.fetch(url, {
      method: "post",
      contentType: "application/json",
      headers: { Authorization: "Bearer " + accessToken },
      payload: JSON.stringify(buildRequest),
      muteHttpExceptions: true
    });

    if (response.getResponseCode() === 200) {
      return CardService.newActionResponseBuilder()
        .setNotification(CardService.newNotification().setText("🚀 Update initiated! Your backend is being rebuilt and redeployed. Please check back in 2-3 minutes."))
        .build();
    } else {
      console.error("Cloud Build Error:", response.getContentText());
      // Fallback to manual if API fails (e.g., missing API enable or scope)
      return showSEMDeployment(e);
    }
  } catch (err) {
    console.error("Update Trigger failed:", err);
    return showSEMDeployment(e);
  }
}

/**
 * Action handler for syncing to MongoDB.
 */
function onSyncMongoDBSEM(e: any) {
  const userEmail = Session.getActiveUser().getEmail();
  const cloudRunUrl = getCloudRunUrl();
  
  if (cloudRunUrl.includes("putchakai.com")) {
    return CardService.newActionResponseBuilder()
      .setNotification(CardService.newNotification().setText("Please deploy the agent first."))
      .build();
  }

  try {
    // 1. Get last sync timestamp
    const lastSyncUrl = `${cloudRunUrl}/mongodb/last_sync?user_email=${encodeURIComponent(userEmail)}`;
    const lastSyncResponse = UrlFetchApp.fetch(lastSyncUrl);
    const lastSyncData = JSON.parse(lastSyncResponse.getContentText());
    let lastSync = lastSyncData.last_sync;

    // 2. Search for emails
    let query = "";
    if (lastSync) {
      // Gmail search uses seconds for 'after'
      const afterTimestamp = Math.floor(new Date(lastSync).getTime() / 1000);
      query = `after:${afterTimestamp}`;
    }

    const threads = GmailApp.search(query, 0, 50); // Limit to 50 threads for now to avoid timeouts
    const emailsToSync = [];

    threads.forEach(thread => {
      const messages = thread.getMessages();
      messages.forEach(msg => {
        emailsToSync.push({
          message_id: msg.getId(),
          subject: msg.getSubject(),
          sender: msg.getFrom(),
          date: msg.getDate().toISOString(),
          body: msg.getPlainBody()
        });
      });
    });

    if (emailsToSync.length === 0) {
      return CardService.newActionResponseBuilder()
        .setNotification(CardService.newNotification().setText("No new emails to sync."))
        .build();
    }

    // 3. Send to Cloud Run in batches
    const syncUrl = `${cloudRunUrl}/mongodb/sync?user_email=${encodeURIComponent(userEmail)}`;
    const batchSize = 10;
    let syncedCount = 0;

    for (let i = 0; i < emailsToSync.length; i += batchSize) {
      const batch = emailsToSync.slice(i, i + batchSize);
      const options = {
        method: "post" as any,
        contentType: "application/json",
        payload: JSON.stringify(batch),
        muteHttpExceptions: true
      };
      const response = UrlFetchApp.fetch(syncUrl, options);
      if (response.getResponseCode() === 200) {
        syncedCount += batch.length;
      }
    }

    const now = new Date().toLocaleString();
    return CardService.newActionResponseBuilder()
      .setNavigation(
        CardService.newNavigation().updateCard(
          createSmartEmailManagerCard("Success", now, "100", now, `Successfully synced ${syncedCount} emails.`),
        ),
      )
      .setNotification(
        CardService.newNotification().setText(`Synced ${syncedCount} emails to MongoDB.`),
      )
      .build();

  } catch (err) {
    console.error("Sync Error:", err);
    return CardService.newActionResponseBuilder()
      .setNotification(CardService.newNotification().setText("Failed to sync emails: " + err.toString()))
      .build();
  }
}

/**
 * Navigation function to show the Smart Email Manager card.
 */
function showSmartEmailManager(e: any) {
  const userEmail = Session.getActiveUser().getEmail();
  const cloudRunUrl = getCloudRunUrl();
  let syncTimestamp = "N/A";
  let connectionStatus = "Not verified";
  let connectionTimestamp = "N/A";

  if (!cloudRunUrl.includes("putchakai.com")) {
    try {
      // Check connection status
      const statusUrl = `${cloudRunUrl}/mongodb/status?user_email=${encodeURIComponent(userEmail)}`;
      const statusResponse = UrlFetchApp.fetch(statusUrl, { muteHttpExceptions: true });
      if (statusResponse.getResponseCode() === 200) {
        const statusData = JSON.parse(statusResponse.getContentText());
        if (statusData.logged_in) {
          connectionStatus = "Success";
          connectionTimestamp = new Date().toLocaleString(); // Or get from DB if stored
        }
      }

      // Get last sync timestamp
      const lastSyncUrl = `${cloudRunUrl}/mongodb/last_sync?user_email=${encodeURIComponent(userEmail)}`;
      const lastSyncResponse = UrlFetchApp.fetch(lastSyncUrl, { muteHttpExceptions: true });
      if (lastSyncResponse.getResponseCode() === 200) {
        const lastSyncData = JSON.parse(lastSyncResponse.getContentText());
        if (lastSyncData.last_sync) {
          syncTimestamp = new Date(lastSyncData.last_sync).toLocaleString();
        }
      }
    } catch (err) {
      console.error("Error fetching SEM status:", err);
    }
  }

  return CardService.newActionResponseBuilder()
    .setNavigation(
      CardService.newNavigation().pushCard(
        createSmartEmailManagerCard(connectionStatus, connectionTimestamp, syncTimestamp !== "N/A" ? "100" : "0", syncTimestamp),
      ),
    )
    .build();
}
